### ISSUE TITLE
0.53 release to CPAN is missing Windows 10 version logic intended for that release

### ISSUE THREAD

**Issue by richardleach** [perl-libwin32/win32#24]
The changelog for 0.53 mentions functionality added to Win32.pm and t\GetOSName.t in master, but those changes were actually not included in the 0.53 release that's on CPAN (at least, not as shown at https://metacpan.org/release/Win32/source/Win32.pm).
```
0.53    [2019-08-05]
        - improve Win32::GetOSDisplayName
        - added Win2016/2019 detection and version information by
          Richard Leach [PR/15]
        - Include wchar.h to allow building with g++ by Tony Cook [rt#127836]
```

e.g. In Win32.pm, the version handling branch just has the following for Win10:
```
        elsif ($major == 10) {
            $os = '10';
        }
```
rather than the detection mentioned in the changelog.
Similarly, the `@win10_tests` are missing from t\GetOSName.t at https://metacpan.org/source/JDB/Win32-0.53/t/GetOSName.t

**Comment by jandubois** [comment]
The 0.53 includes your changes from #15, which were merged in #19, so I think the changelog is correct.

Not yet merged is #21. I forgot to add my review comments to that PR, but will try to do this soon.
