### ISSUE TITLE
Failure noticed on Perl5 test suite cygwin 

### ISSUE THREAD

**Issue by atoomic** [perl-libwin32/win32#32]
`Win32/t/Unicode` is currently failing on blead 

Can be noticed here for example: 
https://github.com/Perl/perl5/runs/4857064214?check_suite_focus=true

```
cpan/Win32/t/CodePage ............................................ ok
2707
cpan/Win32/t/CreateFile .......................................... ok
2708
cpan/Win32/t/ExpandEnvironmentStrings ............................ ok
2709
cpan/Win32/t/GetCurrentThreadId .................................. ok
2710
cpan/Win32/t/GetFileVersion ...................................... skipped
2711
cpan/Win32/t/GetFolderPath ....................................... ok
2712
cpan/Win32/t/GetFullPathName ..................................... ok
2713
cpan/Win32/t/GetLongPathName ..................................... ok
2714
cpan/Win32/t/GetOSName ........................................... ok
2715
cpan/Win32/t/GetOSVersion ........................................ ok
2716
cpan/Win32/t/GetShortPathName .................................... ok
2717
cpan/Win32/t/GuidGen ............................................. ok
2718
cpan/Win32/t/Names ............................................... ok
2719
cpan/Win32/t/Privileges .......................................... ok
2720
# Test 10 got: <UNDEF> (t/Unicode.t at line 93)
2721
#    Expected: "D:\\a\\perl5\\perl5\\cygwin\\home\\runneradmin\\work\\cpan\\Win32\\Foo \x{394}\x{419} Bar \x{5E7}\x{645} Baz"
2722
#  t/Unicode.t line 93 is: ok(Win32::GetLongPathName($subdir), $long);
2723
cpan/Win32/t/Unicode ............................................. FAILED at test 10
2724
cpan/Win32API-File/t/file ........................................ ok
2725
cpan/Win32API-File/t/tie ......................................... ok
```

**Comment by xenu** [comment]
#31 has already fixed this bug. The CI run you linked is for outdated blead that doesn't contain that commit.

**Comment by atoomic** [comment]
`blead` is currently running `0.58` which is when the problem started
this is a minor issue from using the `skip` function... the test is not really skipped due to a lack of wrapper around it lol 
so the function is called when it should not

**Comment by atoomic** [comment]
I was wrong this is fixed by `0.58` and was reading to updated code.
I still think we should add a wrapper around a code we try to skip to do not run it.

**Comment by jandubois** [comment]
> I still think we should add a wrapper around a code we try to skip to do not run it.

Why does it matter? It will return an unexpected value, probably `undef`, but we know this, so won't compare it to the "expected" value.

What benefit does the wrapper provide beyond obfuscation? I think the code is clear as-is.

**Comment by atoomic** [comment]
I agree with you in this case it does not matter that much as the string compare will just be wrong
but IMO you would expect a skip test to do not run any code at all.

**Comment by jandubois** [comment]
> the string compare will just be wrong

There should not be any string compare. From `perldoc Test`:

```
    "skip(*skip_if_true*, *args...*)"
        This is used for tests that under some conditions can be skipped.
        It's basically equivalent to:

          if( $skip_if_true ) {
            ok(1);
          } else {
            ok( args... );
          }
```

So yes, the arguments will be evaluated, but their values will be ignored. I fail to understand what the issue is, as long as the evaluation of the arguments is free of side-effects. Are you trying to save a couple of nanoseconds in a testsuite?

**Comment by atoomic** [comment]
Sorry I do not express my thought correctly and used a shortcut. The compare itself is not performed but the function is called and interpreted... which is I think incorrect.

I'm not trying to save any time, but on skip you should not run the code by design

a traditional skip would be written like
```
SKIP: {
    skip reason => 42 if ...;
    boom()
}
```

here with the current syntax, we are going to call the function `call_boom_or_not` in all cases.
```
skip( $if, call_boom_or_not() )
```
a more appropriate way to write it is to do 
```
skip( $if, sub { call_boom_or_not() } )
```
so the function `call_boom_or_not` is never call.

Currently in this case this not an issue at this point, but IMO skip should skip the code...

**Comment by jandubois** [comment]
> skip you should not run the code by design

You keep on saying this, but `perldoc Test` explicitly says:

```
          # A test to be skipped unless under MSWin (i.e., run only under
          # MSWin)
          skip($unless_MSWin, thing($foo), thing($bar) );
[...]
        Note that in the above cases, "thing($foo)" and "thing($bar)" *are*
        evaluated -- but as long as the "skip_if_true" is true, then we
        "skip(...)" just tosses out their value (i.e., not bothering to
        treat them like values to "ok(...)". But if you need to *not* eval
        the arguments when skipping the test, use this format:
[...]
        or even this, which is basically equivalent:

          skip( $unless_MSWin,
            sub { thing($foo) }, sub { thing($bar) }
          );
```

which essentially says that you only wrap the calls if you **need** to not call them. And I happen to agree with the docs: especially for tests I prefer readability to optimization (as long as the code is still correct).

Where would you draw the line, would you wrap string interpolation into a `sub` to make sure the interpolation doesn't happen when the test is skipped?

```perl
    skip($cond, sub { foo() }, sub { "foo: $foo" });
```

As long as `foo()` doesn't have side-effects, or takes more than a few seconds, and as long as `$foo` is not a tied variable, I would rather write:

```perl
    skip($cond, foo(), "foo: $foo");
```

because it is easier to read and quicker to understand.

Now, given all the cruft in this decades-old module, I'm happy to agree that all this doesn't really matter, and if it really makes you happy, I can apply your change to indulge you. But it still rubs me the wrong way that you insists this is the way it **has** to be done, the Test module docs to the contrary. Whatever happened to TIMTOWTDI? 😸

**Comment by atoomic** [comment]
Sorry for my later reply. First thanks a lot for your detail answer and time on this.

I think we both agree that this is not needed. 

I ran into it and was thinking this was the bug as  this was the exact same line of the failure reported by the CI. Before realizing that the upstream update was fixing it.

I understand our difference of point of view, and as long as calling the function is not hurting this is fine.
I was just trying to advocate a more generic philosophy: If you are not going to test a function, you should probably not even considering running it... Kind of skip vs todo using Test::More & co.

For that very example, it does not matter, until it does :-) and I m really incline to close the PR / Case and leave the test as it.

Thanks a lot for your time once again
really appreciate
nicolas

**Comment by jandubois** [comment]
Thank you for creating a PR to fix an issue, even if it ultimately wasn't necessary!
